language: java
cache:
  directories:
    - $HOME/.m2
services: mysql
jdk: oraclejdk8
sudo: false
install: true
before_script: mysql -uroot < src/test/resources/schema.sql
script: mvn -Dspring.datasource.password= verify
