build: off
services:
  mysql
before_test:
  - 'xcopy /S /Y .appveyor\* src\main\'
  - 'SET MINGW_HOME=C:\MinGW'
  - 'SET PATH=%MINGW_HOME%\bin;%PATH%'
test_script:
  - mvnw -Dspring.datasource.password=Password12! -Djna.nosys=true clean install -B
cache:
  - '%USERPROFILE%\.m2'
after_test:
  - 'SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%'
  - pip install codecov
  - codecov -X gcov -f target/site/jacoco/jacoco.xml
