ckfinder:
  license.strategy: host
  image:
    max-width: 1600
    max-height: 1200
  types:
    Files:
      allowed-extensions: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip
      denied-extensions: exe,jsp,jspx,asp,aspx
    Images.allowed-extensions: bmp,gif,jpeg,jpg,png
  access-controls:
  - role: '*'
    resource-type: '*'
    folder: /
    folder-view: true
    folder-create: true
    folder-rename: true
    folder-delete: true
    file-view: true
    file-upload: true
    file-rename: true
    file-delete: true
  thumbs.direct-access: true
  check-double-extension: false
  check-size-after-scaling: true
  force-ascii: true
  secure-image-uploads: true
  servlet.path: /webjars/ckfinder/2.6.2.1/core/connector/java/connector.java
